[build]
  publish = "."

# Redirects for language
[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200
  force = false

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
